### ISSUE TITLE
Rename file not works

### ISSUE THREAD

**Issue by mort3za** [sigsergv/SublimeFileOpTabContextMenu#4]
Rename file on tab context menu not works. Without any error or message on status bar.

ST3 3047

**Comment by sigsergv** [comment]
Are you sure? File rename prompt appears as a thin line at the bottom of the application, see this screenshot for example:

![screenshot](https://cloud.githubusercontent.com/assets/1030732/9702394/2f040310-5474-11e5-937a-de837c11ccc0.png)

**Comment by mort3za** [comment]
Yes, I'm sure. My OS is win8.1x64

**Comment by sigsergv** [comment]
Just checked on latest windows stable version (1083), rename is working fine.

Could you try to reproduce bug with debug console opened? Ctrl+` or *View→Show Console* and then try to rename file again.

**Comment by stephen147** [comment]
I'm seeing this issue also.  When I have the console open nothing happens. Latest windows 10 and latest ST.

**Comment by stephen147** [comment]
Actually, it must be something else causing this as I've tried on a fresh portable build and all seems to be fine.

I wonder what's causing this.

**Comment by sigsergv** [comment]
It could be caused by some addon or configuration option. If you provide addons list you are using plus complete config I could check it.

**Comment by stephen147** [comment]
I would have to bundle the whole ST folder and upload it as I've many addons and configs. I'll post a link in a while with that.

**Comment by stephen147** [comment]
Found the culprit.

It's [SideBarEnhancements ](https://packagecontrol.io/packages/SideBarEnhancements) that causes this. As soon as I disable that the issue goes away.

**Comment by sigsergv** [comment]
Thank you! It will help to find a bug.

**Comment by sigsergv** [comment]
I've updated package and submitted a new version (1.6.0), it should be available soon.

SideBarEnhancements redefined side bar functions including one that rename files.

**Comment by stephen147** [comment]
Thanks. tested and working now.
